# This is a workflow to build the teachers edition
name: Build Teachers Edition

on:
  push:
    workflow_dispatch:
jobs:
  makepdfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm install
      - name: Build PDF
        run: npm run build
      - uses: actions/upload-artifact@v1
        with:
          name: teacher-edition
          path: build
